import { ReservationAccordion } from "./model";


export const RESERVATION_ACCORDION_LIST: ReservationAccordion[] = [
    {
        groupLabel: 'Reading',
        title: 'Penske Reading',
        identifier: '0666-10',
        reservations: [
            {
                id :1,
                name: 'John Stone 9.30',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'red',
                assigned: false,
                reservationTime: new Date('2025-04-23T09:30:00'),
            },
            {
                id :2,
                name: 'John Stone 9.29',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T09:29:00'),
            },
            {
                id:3,
                name: 'John Stone 12.50',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T12:50:00'),
            },
            {
                id:4,
                name: 'John Stone 12.30',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T12:30:00'),
            },
            { 
                id:5,
                name: 'John Stone 12.25',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T12:25:00'),
            },
            {
                id:6,
                name: 'John Stone 11.00',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T11:00:00'),
            },
            {
                id:7,
                name: 'John Stone 11.25',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T11:25:00'),
            },
            {
                id:8,
                name: 'John Stone 11.35',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T11:35:00'),
            },
            {
                id:9,
                name: 'John Stone 12.31',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T12:31:00'),
            },
            {
                id:10,
                name: 'John Stone 13.50',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T13:50:00'),
            },
            {
                id:11,
                name: 'John Stone 9.15',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T09:15:00'),
            },
            {
                id:12,
                name: '10.00',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'red',
                assigned: true,
                reservationTime: new Date('2025-04-23T10:00:00'),
            },
            {
                id:13,
                name: '9.00',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T09:00:00'),
            },
            {
                id:14,
                name: '9.31',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T09:31:00'),
            },
            {
                id:15,
                name: '9.45',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T09:45:00'),
            },
            {
                id:16,
                name: 'Emily Rose 10:15',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'blue',
                assigned: true,
                reservationTime: new Date('2025-04-23T10:15:00'),
            },
            {
                id:17,
                name: 'Emily Rose 10:30',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'blue',
                assigned: true,
                reservationTime: new Date('2025-04-23T10:30:00'),
            },
            {
                id:18,
                name: 'Sarah Connor 14:00',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T14:00:00'),
            },
            {
                id:19,
                name: 'Chris Jordan 10:45',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'gray',
                assigned: true,
                reservationTime: new Date('2025-04-23T10:45:00'),
            },
            {
                id:20,
                name: 'Chris Jordan 15:20',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'gray',
                assigned: true,
                reservationTime: new Date('2025-04-23T15:20:00'),
            },
            {
                id:21,
                name: 'Chris Jordan 15:29',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'gray',
                assigned: true,
                reservationTime: new Date('2025-04-23T15:29:00'),
            },
            {
                id:22,
                name: 'Chris Jordan 15:31',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'gray',
                assigned: true,
                reservationTime: new Date('2025-04-23T15:31:00'),
            },
            {
                id:23,
                name: 'Michael Bay 16:00',
                unitNumber: '#544387',
                towNumber: '#987654',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T16:00:00'),
            },
        ],
    },
    {
        groupLabel: 'Lancaster',
        title: 'Penske Lancaster',
        identifier: '0677-11',
        reservations: [

            {
                id:100,
                name: '14:15',
                unitNumber: '#100004',
                towNumber: '#111222',
                vehicleType: 'Refrigerator',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: false,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T14:15:00'),
            },
            {
                id:101,
                name: '14:45',
                unitNumber: '#100005',
                towNumber: '#333444',
                vehicleType: 'Box Truck',
                tripType: 'Lease',
                customerType: 'Commercial',
                hasPhone: false,
                hasFavorite: true,
                hasWarning: true,
                accentColor: 'red',
                assigned: false,
                reservationTime: new Date('2025-04-23T14:45:00'),
            },

            {
                id:102,
                name: '13:00',
                unitNumber: '#100001',
                towNumber: '#123123',
                vehicleType: 'Flatbed',
                tripType: 'One Way',
                customerType: 'Commercial',
                hasPhone: false,
                hasFavorite: true,
                hasWarning: true,
                accentColor: 'red',
                assigned: true,
                reservationTime: new Date('2025-04-23T13:00:00'),
            },
            {
                id:103,
                name: '13:20',
                unitNumber: '#100002',
                towNumber: '#456456',
                vehicleType: 'Box Truck',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: false,
                hasWarning: false,
                accentColor: 'blue',
                assigned: true,
                reservationTime: new Date('2025-04-23T13:20:00'),
            },
            {
                id:104,
                name: '13:45',
                unitNumber: '#100003',
                towNumber: '#789789',
                vehicleType: 'Pickup',
                tripType: 'Lease',
                customerType: 'Substitute',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'gray',
                assigned: false,
                reservationTime: new Date('2025-04-23T13:45:00'),
            },
            {
                id:105,
                name: '16:00',
                unitNumber: '#100006',
                towNumber: '#555666',
                vehicleType: 'Flatbed',
                tripType: 'One Way',
                customerType: 'Substitute',
                hasPhone: true,
                hasFavorite: false,
                hasWarning: false,
                accentColor: 'blue',
                assigned: true,
                reservationTime: new Date('2025-04-23T16:00:00'),
            },
            {
                id:106,
                name: '16:20',
                unitNumber: '#100007',
                towNumber: '#777888',
                vehicleType: 'Pickup',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: false,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T16:20:00'),
            },
            {
                id:107,
                name: '16:45',
                unitNumber: '#100008',
                towNumber: '#999000',
                vehicleType: 'Refrigerator',
                tripType: 'Lease',
                customerType: 'Commercial',
                hasPhone: true,
                hasFavorite: false,
                hasWarning: true,
                accentColor: 'gray',
                assigned: true,
                reservationTime: new Date('2025-04-23T16:45:00'),
            },

            {
                id:108,
                name: '18:00',
                unitNumber: '#100009',
                towNumber: '#222333',
                vehicleType: 'Box Truck',
                tripType: 'Round Trip',
                customerType: 'Consumer',
                hasPhone: true,
                hasFavorite: true,
                hasWarning: false,
                accentColor: 'green',
                assigned: true,
                reservationTime: new Date('2025-04-23T18:00:00'),
            },
            {
                id:109,
                name: '18:45',
                unitNumber: '#100010',
                towNumber: '#444555',
                vehicleType: 'Pickup',
                tripType: 'Lease',
                customerType: 'Substitute',
                hasPhone: false,
                hasFavorite: false,
                hasWarning: true,
                accentColor: 'red',
                assigned: false,
                reservationTime: new Date('2025-04-23T18:45:00'),
            },
        ],
    },
];
